name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: PixelMeshifier
        path: src/dist/windows

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses:actions/checkout@v2
      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: src
      -uses: actions/upload-artifact@v2
      - with:
          name: PixelMeshifier
          path: src/dist/linux
